name: "Commax Wallpad"
description: "코맥스 애드온 TCP Socket Ver"
version: "1.0.3"
slug: "commax_wallpad"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  mqtt_topic_prefix: "devcommax"
  mqtt_broker_url: "192.168.0.34"
  mqtt_port: 1883
  mqtt_username: "dev"
  mqtt_password: "password"
  ew11_host: "192.168.0.37"
  ew11_port: 8899
schema:
  mqtt_topic_prefix: "str"
  mqtt_broker_url: "str"
  mqtt_port: "int"
  mqtt_username: "str"
  mqtt_password: "password"
  ew11_host: "str"
  ew11_port: "int"
map:
  - "share:rw"